meta_product_name: "GigGoers"
meta_title: "GigGoers - Você no lugar quando a música começar"
meta_description: "Um aplicativo dinâmico e interativo para descobrir e participar de eventos, com recursos de busca, filtragem por gênero e ordenação personalizada"
meta_image: "cover.png" # should exist in `app/assets/images/`
